INPUT = <<~TEXT.split("\n")
striped_white_bag CONTAIN drab_silver_bag(4)
drab_silver_bag CONTAIN no_other_bag
pale_plum_bag CONTAIN dark_black_bag(1)
muted_gold_bag CONTAIN wavy_red_bag(1), mirrored_violet_bag(3), bright_gold_bag(5), plaid_white_bag(5)
muted_teal_bag CONTAIN pale_beige_bag(2), clear_beige_bag(5), dotted_gold_bag(2), posh_cyan_bag(4)
posh_coral_bag CONTAIN light_silver_bag(1), dull_blue_bag(2), dim_fuchsia_bag(3), dotted_magenta_bag(2)
faded_black_bag CONTAIN light_silver_bag(4)
muted_lavender_bag CONTAIN pale_gold_bag(1)
clear_fuchsia_bag CONTAIN dull_gray_bag(1), shiny_indigo_bag(2), posh_olive_bag(3), vibrant_plum_bag(5)
shiny_olive_bag CONTAIN dotted_gold_bag(1), bright_violet_bag(5)
vibrant_lavender_bag CONTAIN dotted_aqua_bag(3), pale_chartreuse_bag(4), mirrored_blue_bag(5)
pale_fuchsia_bag CONTAIN pale_crimson_bag(5), dull_teal_bag(2)
clear_lavender_bag CONTAIN shiny_fuchsia_bag(5), wavy_teal_bag(5)
light_chartreuse_bag CONTAIN mirrored_yellow_bag(5), bright_maroon_bag(3)
mirrored_white_bag CONTAIN bright_gray_bag(1), plaid_blue_bag(4)
dark_teal_bag CONTAIN bright_maroon_bag(4), plaid_bronze_bag(5), dark_brown_bag(1)
wavy_yellow_bag CONTAIN dim_silver_bag(4), striped_tomato_bag(1), clear_chartreuse_bag(5)
dark_turquoise_bag CONTAIN clear_plum_bag(4)
posh_gray_bag CONTAIN faded_purple_bag(2), faded_orange_bag(2)
wavy_tomato_bag CONTAIN dark_purple_bag(1)
vibrant_gray_bag CONTAIN muted_gray_bag(3), dark_fuchsia_bag(1), posh_white_bag(5), posh_tomato_bag(5)
light_crimson_bag CONTAIN dotted_chartreuse_bag(2)
dull_gray_bag CONTAIN muted_brown_bag(4), shiny_blue_bag(2), dim_crimson_bag(4)
drab_red_bag CONTAIN bright_cyan_bag(2), pale_brown_bag(1)
dotted_salmon_bag CONTAIN mirrored_indigo_bag(5)
vibrant_green_bag CONTAIN dark_coral_bag(2)
light_magenta_bag CONTAIN clear_bronze_bag(4), dull_teal_bag(4), posh_salmon_bag(4)
vibrant_purple_bag CONTAIN posh_plum_bag(4), bright_gray_bag(2)
posh_lime_bag CONTAIN plaid_yellow_bag(3), posh_salmon_bag(4)
bright_white_bag CONTAIN dull_aqua_bag(4), shiny_silver_bag(1)
faded_blue_bag CONTAIN muted_cyan_bag(5), mirrored_coral_bag(2)
dim_green_bag CONTAIN posh_lavender_bag(2)
faded_gray_bag CONTAIN dark_gold_bag(2), drab_turquoise_bag(1)
wavy_black_bag CONTAIN dim_fuchsia_bag(4), muted_orange_bag(1), drab_salmon_bag(4)
plaid_plum_bag CONTAIN dotted_tomato_bag(5), shiny_beige_bag(1)
bright_tan_bag CONTAIN posh_salmon_bag(2)
wavy_gold_bag CONTAIN faded_olive_bag(1), vibrant_black_bag(5), dull_orange_bag(3)
dull_fuchsia_bag CONTAIN faded_crimson_bag(1), vibrant_white_bag(5)
shiny_maroon_bag CONTAIN dull_lavender_bag(5), dim_white_bag(1)
wavy_white_bag CONTAIN light_teal_bag(5), dim_salmon_bag(4), dotted_red_bag(3), dark_red_bag(5)
dim_cyan_bag CONTAIN muted_orange_bag(1)
muted_cyan_bag CONTAIN dull_turquoise_bag(4), posh_gray_bag(5), clear_turquoise_bag(5), shiny_plum_bag(1)
posh_violet_bag CONTAIN plaid_crimson_bag(5), muted_purple_bag(5), wavy_beige_bag(1), mirrored_orange_bag(2)
faded_purple_bag CONTAIN plaid_blue_bag(3), dull_lavender_bag(1), muted_orange_bag(1), dotted_tomato_bag(2)
wavy_beige_bag CONTAIN dotted_beige_bag(1)
dim_black_bag CONTAIN wavy_blue_bag(1), plaid_black_bag(1), pale_lavender_bag(3), light_violet_bag(2)
dotted_lavender_bag CONTAIN plaid_blue_bag(1), dim_crimson_bag(5)
dark_yellow_bag CONTAIN posh_green_bag(3)
wavy_salmon_bag CONTAIN clear_aqua_bag(1), mirrored_crimson_bag(3), pale_magenta_bag(3), dull_teal_bag(2)
clear_silver_bag CONTAIN faded_tan_bag(3), faded_aqua_bag(5), clear_tomato_bag(1)
vibrant_bronze_bag CONTAIN faded_maroon_bag(1), plaid_indigo_bag(4), bright_purple_bag(2), dim_violet_bag(5)
pale_brown_bag CONTAIN dull_lavender_bag(1), clear_turquoise_bag(2)
faded_salmon_bag CONTAIN pale_silver_bag(1)
dark_gray_bag CONTAIN pale_teal_bag(2)
posh_red_bag CONTAIN faded_black_bag(3), dull_red_bag(2)
dim_indigo_bag CONTAIN bright_green_bag(3), dotted_tomato_bag(2), bright_magenta_bag(5)
dull_maroon_bag CONTAIN light_green_bag(5)
wavy_teal_bag CONTAIN faded_tan_bag(5), clear_orange_bag(4)
pale_chartreuse_bag CONTAIN bright_blue_bag(5), light_indigo_bag(3), shiny_white_bag(3), wavy_bronze_bag(3)
mirrored_gray_bag CONTAIN vibrant_tomato_bag(4), dark_red_bag(1), drab_silver_bag(5), posh_magenta_bag(3)
dark_lavender_bag CONTAIN dotted_white_bag(4), vibrant_chartreuse_bag(5), dim_teal_bag(2)
shiny_turquoise_bag CONTAIN dim_lime_bag(3), bright_cyan_bag(5), pale_green_bag(2)
shiny_indigo_bag CONTAIN dark_fuchsia_bag(2), posh_chartreuse_bag(4)
pale_crimson_bag CONTAIN mirrored_silver_bag(5), posh_black_bag(2)
light_salmon_bag CONTAIN vibrant_orange_bag(2), dotted_red_bag(2)
plaid_orange_bag CONTAIN dotted_turquoise_bag(1), vibrant_brown_bag(4)
dim_maroon_bag CONTAIN shiny_gold_bag(5), mirrored_maroon_bag(4)
muted_green_bag CONTAIN plaid_plum_bag(1)
faded_indigo_bag CONTAIN faded_purple_bag(3), vibrant_indigo_bag(4), light_coral_bag(1)
dull_blue_bag CONTAIN dull_salmon_bag(5), wavy_magenta_bag(2)
vibrant_black_bag CONTAIN light_coral_bag(1), vibrant_cyan_bag(5), dim_magenta_bag(3)
striped_lime_bag CONTAIN striped_maroon_bag(1), vibrant_brown_bag(2)
drab_brown_bag CONTAIN faded_olive_bag(1), dotted_beige_bag(5)
dark_plum_bag CONTAIN faded_brown_bag(5)
clear_olive_bag CONTAIN dull_aqua_bag(3), drab_yellow_bag(5)
wavy_crimson_bag CONTAIN posh_plum_bag(2), dull_aqua_bag(2), shiny_teal_bag(5), vibrant_purple_bag(2)
mirrored_olive_bag CONTAIN wavy_gold_bag(2)
dim_crimson_bag CONTAIN no_other_bag
faded_plum_bag CONTAIN plaid_indigo_bag(1)
light_maroon_bag CONTAIN vibrant_orange_bag(3), clear_olive_bag(2), clear_brown_bag(3), pale_black_bag(1)
posh_white_bag CONTAIN dull_green_bag(3), clear_brown_bag(3)
drab_black_bag CONTAIN shiny_turquoise_bag(2)
light_purple_bag CONTAIN pale_black_bag(2), light_silver_bag(5), drab_coral_bag(1)
pale_yellow_bag CONTAIN vibrant_orange_bag(2), posh_black_bag(5), vibrant_tomato_bag(2), dotted_lavender_bag(3)
dull_cyan_bag CONTAIN wavy_beige_bag(5), dull_yellow_bag(1), drab_lime_bag(3), drab_chartreuse_bag(3)
drab_lavender_bag CONTAIN plaid_black_bag(2), dotted_gray_bag(4), dim_silver_bag(1), shiny_gold_bag(2)
striped_brown_bag CONTAIN light_maroon_bag(5), light_red_bag(3), clear_indigo_bag(3)
drab_tomato_bag CONTAIN light_black_bag(2), clear_salmon_bag(2)
dotted_red_bag CONTAIN dim_salmon_bag(4), striped_indigo_bag(5)
vibrant_teal_bag CONTAIN bright_black_bag(5), dark_purple_bag(1), bright_turquoise_bag(2)
striped_teal_bag CONTAIN mirrored_silver_bag(4)
dull_beige_bag CONTAIN clear_olive_bag(4), light_teal_bag(4), bright_plum_bag(3), dotted_lavender_bag(4)
light_violet_bag CONTAIN dull_lavender_bag(2), bright_gray_bag(4), vibrant_orange_bag(5), wavy_magenta_bag(3)
dim_brown_bag CONTAIN clear_plum_bag(2), shiny_teal_bag(2), posh_salmon_bag(2)
striped_magenta_bag CONTAIN posh_turquoise_bag(4), pale_cyan_bag(3), faded_indigo_bag(3)
bright_orange_bag CONTAIN plaid_gray_bag(4), dark_black_bag(4), faded_red_bag(4), bright_black_bag(4)
muted_olive_bag CONTAIN dotted_crimson_bag(2), faded_lavender_bag(4), vibrant_gray_bag(2)
plaid_teal_bag CONTAIN light_yellow_bag(2), drab_cyan_bag(4), light_green_bag(3)
faded_fuchsia_bag CONTAIN posh_silver_bag(1), drab_chartreuse_bag(4), drab_teal_bag(4)
dim_silver_bag CONTAIN pale_turquoise_bag(1)
bright_lime_bag CONTAIN striped_silver_bag(1), muted_teal_bag(5), shiny_tan_bag(1), dark_silver_bag(1)
dotted_green_bag CONTAIN posh_green_bag(3), drab_yellow_bag(1)
drab_purple_bag CONTAIN bright_violet_bag(5), posh_tomato_bag(1)
dull_bronze_bag CONTAIN mirrored_black_bag(4)
striped_tomato_bag CONTAIN posh_gray_bag(1), posh_magenta_bag(2)
bright_crimson_bag CONTAIN light_olive_bag(2), clear_tan_bag(4), drab_fuchsia_bag(3)
bright_turquoise_bag CONTAIN pale_teal_bag(4), drab_silver_bag(3)
shiny_lavender_bag CONTAIN striped_lime_bag(2), plaid_tomato_bag(2), faded_orange_bag(1), wavy_magenta_bag(5)
light_tomato_bag CONTAIN dotted_olive_bag(5)
wavy_magenta_bag CONTAIN no_other_bag
vibrant_fuchsia_bag CONTAIN posh_brown_bag(5), plaid_indigo_bag(5)
dark_tomato_bag CONTAIN shiny_plum_bag(3)
pale_bronze_bag CONTAIN plaid_black_bag(5), vibrant_brown_bag(5), dim_lime_bag(2), muted_bronze_bag(4)
striped_fuchsia_bag CONTAIN muted_brown_bag(3), pale_chartreuse_bag(2), dim_magenta_bag(1)
dark_brown_bag CONTAIN clear_bronze_bag(4)
posh_teal_bag CONTAIN dotted_plum_bag(5), drab_gray_bag(2), dull_fuchsia_bag(3)
wavy_turquoise_bag CONTAIN dull_lavender_bag(1)
striped_maroon_bag CONTAIN muted_yellow_bag(4), clear_orange_bag(4), vibrant_orange_bag(4)
shiny_green_bag CONTAIN muted_brown_bag(3), vibrant_black_bag(1), wavy_cyan_bag(4), posh_brown_bag(3)
plaid_salmon_bag CONTAIN mirrored_indigo_bag(4), wavy_white_bag(2), mirrored_bronze_bag(5), light_coral_bag(3)
dotted_magenta_bag CONTAIN light_olive_bag(2), dark_red_bag(2), clear_green_bag(4), dim_plum_bag(3)
light_orange_bag CONTAIN dark_plum_bag(5), bright_maroon_bag(3), dotted_lime_bag(2)
clear_brown_bag CONTAIN dim_white_bag(3), posh_magenta_bag(2)
vibrant_turquoise_bag CONTAIN striped_yellow_bag(2), mirrored_crimson_bag(1)
muted_coral_bag CONTAIN wavy_gold_bag(4), dim_tan_bag(2), shiny_green_bag(1)
plaid_crimson_bag CONTAIN dull_aqua_bag(1)
vibrant_plum_bag CONTAIN striped_tomato_bag(4), striped_turquoise_bag(1)
dark_coral_bag CONTAIN posh_black_bag(5), shiny_beige_bag(1), pale_brown_bag(3)
mirrored_brown_bag CONTAIN clear_blue_bag(1), dull_indigo_bag(1)
bright_blue_bag CONTAIN light_violet_bag(2), dotted_tomato_bag(1)
drab_cyan_bag CONTAIN dim_turquoise_bag(2), clear_violet_bag(5)
dotted_coral_bag CONTAIN dotted_aqua_bag(3)
shiny_yellow_bag CONTAIN wavy_cyan_bag(1)
shiny_red_bag CONTAIN shiny_beige_bag(5), dotted_lime_bag(3), dotted_plum_bag(5)
muted_lime_bag CONTAIN dark_turquoise_bag(3), bright_chartreuse_bag(3)
pale_gray_bag CONTAIN dotted_coral_bag(5), wavy_teal_bag(4), clear_aqua_bag(2)
pale_blue_bag CONTAIN dull_salmon_bag(5), posh_bronze_bag(3), vibrant_tomato_bag(2)
dim_turquoise_bag CONTAIN posh_aqua_bag(4), dark_turquoise_bag(2)
pale_turquoise_bag CONTAIN vibrant_brown_bag(5), shiny_maroon_bag(2)
dim_gray_bag CONTAIN faded_tomato_bag(2), faded_indigo_bag(2)
clear_aqua_bag CONTAIN light_turquoise_bag(1), dotted_turquoise_bag(3)
faded_turquoise_bag CONTAIN muted_lime_bag(5)
clear_plum_bag CONTAIN plaid_indigo_bag(2), drab_yellow_bag(5)
vibrant_white_bag CONTAIN bright_violet_bag(2), dark_plum_bag(4), dim_plum_bag(1), plaid_indigo_bag(4)
dark_orange_bag CONTAIN posh_purple_bag(3), clear_orange_bag(5), dim_white_bag(1)
light_olive_bag CONTAIN drab_green_bag(3)
muted_salmon_bag CONTAIN muted_cyan_bag(4)
clear_maroon_bag CONTAIN muted_yellow_bag(2), plaid_crimson_bag(5), clear_turquoise_bag(1)
wavy_orange_bag CONTAIN vibrant_blue_bag(4), posh_brown_bag(4), pale_turquoise_bag(2), shiny_orange_bag(5)
dotted_gold_bag CONTAIN posh_magenta_bag(3), faded_crimson_bag(1), dotted_olive_bag(3), plaid_olive_bag(3)
dull_purple_bag CONTAIN drab_salmon_bag(5), dim_lavender_bag(4)
light_bronze_bag CONTAIN wavy_indigo_bag(2)
muted_turquoise_bag CONTAIN clear_turquoise_bag(5), plaid_violet_bag(4), clear_orange_bag(4), posh_maroon_bag(2)
mirrored_blue_bag CONTAIN clear_chartreuse_bag(4)
drab_tan_bag CONTAIN striped_violet_bag(3), bright_silver_bag(2), dark_bronze_bag(2), mirrored_black_bag(1)
dark_maroon_bag CONTAIN vibrant_orange_bag(1)
drab_yellow_bag CONTAIN vibrant_blue_bag(1), dim_violet_bag(2)
light_cyan_bag CONTAIN posh_beige_bag(4)
vibrant_salmon_bag CONTAIN wavy_gold_bag(3)
muted_orange_bag CONTAIN dotted_tomato_bag(3), vibrant_tomato_bag(4), dull_lavender_bag(5)
dull_turquoise_bag CONTAIN wavy_white_bag(1)
dotted_indigo_bag CONTAIN wavy_bronze_bag(3)
dark_red_bag CONTAIN wavy_bronze_bag(4), wavy_turquoise_bag(5)
light_coral_bag CONTAIN clear_tan_bag(4), vibrant_beige_bag(2), dull_lavender_bag(1), shiny_white_bag(5)
mirrored_turquoise_bag CONTAIN clear_fuchsia_bag(5), mirrored_black_bag(3), plaid_tan_bag(4)
mirrored_yellow_bag CONTAIN pale_turquoise_bag(4), wavy_orange_bag(2), drab_coral_bag(3), dim_chartreuse_bag(4)
dotted_fuchsia_bag CONTAIN dim_bronze_bag(4), striped_indigo_bag(4)
dotted_purple_bag CONTAIN posh_maroon_bag(5), dim_yellow_bag(1)
clear_coral_bag CONTAIN dark_olive_bag(5), wavy_bronze_bag(2), light_red_bag(3)
mirrored_teal_bag CONTAIN drab_yellow_bag(3)
faded_green_bag CONTAIN dark_purple_bag(2)
light_lime_bag CONTAIN bright_chartreuse_bag(4), clear_tomato_bag(5), bright_green_bag(2), faded_teal_bag(2)
bright_yellow_bag CONTAIN dull_purple_bag(4), faded_beige_bag(3)
bright_maroon_bag CONTAIN vibrant_blue_bag(2), bright_violet_bag(5), plaid_indigo_bag(5), vibrant_orange_bag(3)
faded_red_bag CONTAIN pale_brown_bag(5), striped_tomato_bag(4), bright_green_bag(2)
muted_maroon_bag CONTAIN dark_tan_bag(1), drab_teal_bag(5), dull_maroon_bag(4)
plaid_coral_bag CONTAIN bright_blue_bag(5), dotted_indigo_bag(1)
dotted_brown_bag CONTAIN dull_beige_bag(1), bright_indigo_bag(2), striped_chartreuse_bag(2), muted_silver_bag(1)
wavy_coral_bag CONTAIN clear_cyan_bag(2), muted_teal_bag(2), faded_red_bag(1), mirrored_silver_bag(2)
faded_coral_bag CONTAIN bright_green_bag(3), bright_cyan_bag(1), plaid_blue_bag(3), wavy_lavender_bag(5)
dim_gold_bag CONTAIN dim_teal_bag(5), vibrant_tomato_bag(1), pale_chartreuse_bag(5), bright_indigo_bag(3)
bright_salmon_bag CONTAIN plaid_chartreuse_bag(5), light_tan_bag(5), vibrant_maroon_bag(5)
wavy_violet_bag CONTAIN bright_green_bag(4)
mirrored_lavender_bag CONTAIN drab_plum_bag(5), drab_turquoise_bag(2), dark_magenta_bag(2)
faded_aqua_bag CONTAIN faded_teal_bag(3), dark_red_bag(1)
muted_yellow_bag CONTAIN mirrored_silver_bag(1), striped_white_bag(1), mirrored_gold_bag(3), muted_gray_bag(1)
pale_coral_bag CONTAIN striped_gray_bag(2), clear_beige_bag(2)
mirrored_cyan_bag CONTAIN pale_beige_bag(1), dim_crimson_bag(4)
dotted_aqua_bag CONTAIN dim_crimson_bag(4), vibrant_beige_bag(3)
dark_white_bag CONTAIN dim_maroon_bag(4), light_olive_bag(1), dull_fuchsia_bag(3), mirrored_maroon_bag(4)
dotted_chartreuse_bag CONTAIN clear_tan_bag(5), clear_white_bag(2), dark_coral_bag(2), faded_brown_bag(4)
mirrored_red_bag CONTAIN faded_violet_bag(5), dark_chartreuse_bag(2)
drab_maroon_bag CONTAIN bright_violet_bag(3)
dark_violet_bag CONTAIN dark_turquoise_bag(5), muted_blue_bag(1), plaid_bronze_bag(4)
dull_silver_bag CONTAIN dotted_lime_bag(4), dotted_silver_bag(3), dull_red_bag(4), pale_white_bag(3)
striped_lavender_bag CONTAIN drab_silver_bag(5)
light_yellow_bag CONTAIN posh_plum_bag(3), bright_olive_bag(3), wavy_crimson_bag(4)
posh_chartreuse_bag CONTAIN bright_violet_bag(2)
pale_green_bag CONTAIN shiny_lime_bag(5), faded_teal_bag(3), posh_gray_bag(5), posh_chartreuse_bag(1)
shiny_lime_bag CONTAIN dull_beige_bag(1), light_aqua_bag(4), dotted_tomato_bag(4)
plaid_tan_bag CONTAIN mirrored_chartreuse_bag(1)
drab_coral_bag CONTAIN posh_gray_bag(5), dull_black_bag(2)
drab_salmon_bag CONTAIN drab_yellow_bag(4), mirrored_green_bag(3)
faded_yellow_bag CONTAIN mirrored_beige_bag(2), bright_turquoise_bag(1), vibrant_black_bag(1)
bright_tomato_bag CONTAIN clear_brown_bag(4)
muted_beige_bag CONTAIN clear_turquoise_bag(1)
striped_black_bag CONTAIN plaid_chartreuse_bag(1)
bright_cyan_bag CONTAIN clear_tomato_bag(5)
striped_coral_bag CONTAIN muted_red_bag(2)
posh_bronze_bag CONTAIN striped_yellow_bag(5)
mirrored_maroon_bag CONTAIN vibrant_tomato_bag(4), bright_green_bag(5), vibrant_maroon_bag(4), striped_violet_bag(4)
dotted_turquoise_bag CONTAIN posh_beige_bag(1), muted_silver_bag(5)
bright_purple_bag CONTAIN drab_silver_bag(5), shiny_blue_bag(5), plaid_bronze_bag(2), faded_magenta_bag(4)
posh_plum_bag CONTAIN striped_white_bag(5), pale_brown_bag(2), wavy_turquoise_bag(1)
dark_crimson_bag CONTAIN dull_black_bag(1), dull_yellow_bag(2), posh_white_bag(1), dotted_lime_bag(3)
plaid_bronze_bag CONTAIN striped_indigo_bag(5), light_indigo_bag(5), wavy_magenta_bag(4), vibrant_blue_bag(3)
clear_red_bag CONTAIN posh_silver_bag(4), dim_aqua_bag(1)
striped_salmon_bag CONTAIN bright_violet_bag(3), faded_olive_bag(4), dim_turquoise_bag(5)
dim_bronze_bag CONTAIN no_other_bag
wavy_brown_bag CONTAIN vibrant_turquoise_bag(4)
wavy_maroon_bag CONTAIN mirrored_bronze_bag(1), posh_fuchsia_bag(2), mirrored_indigo_bag(1)
mirrored_salmon_bag CONTAIN faded_lavender_bag(2)
dark_aqua_bag CONTAIN faded_teal_bag(4), dim_tomato_bag(1)
pale_violet_bag CONTAIN clear_blue_bag(5), plaid_blue_bag(3), dim_teal_bag(5), pale_black_bag(2)
mirrored_crimson_bag CONTAIN posh_magenta_bag(2), dotted_aqua_bag(2), dim_bronze_bag(1)
bright_indigo_bag CONTAIN bright_violet_bag(4)
muted_violet_bag CONTAIN mirrored_maroon_bag(4), dull_red_bag(2), plaid_tomato_bag(4), pale_yellow_bag(1)
shiny_gold_bag CONTAIN vibrant_blue_bag(3), plaid_blue_bag(5), dark_red_bag(2), dull_green_bag(1)
clear_green_bag CONTAIN dotted_lavender_bag(4)
dark_indigo_bag CONTAIN light_lime_bag(2), wavy_brown_bag(3)
muted_fuchsia_bag CONTAIN plaid_green_bag(3)
bright_silver_bag CONTAIN dim_tomato_bag(4), clear_olive_bag(3), dull_teal_bag(1)
plaid_purple_bag CONTAIN dark_silver_bag(4), vibrant_crimson_bag(1), dark_black_bag(4), faded_magenta_bag(3)
clear_chartreuse_bag CONTAIN posh_plum_bag(4)
plaid_tomato_bag CONTAIN wavy_aqua_bag(2), striped_indigo_bag(3), wavy_magenta_bag(1)
posh_cyan_bag CONTAIN drab_green_bag(3), bright_chartreuse_bag(3), muted_gray_bag(3), light_black_bag(2)
posh_turquoise_bag CONTAIN wavy_teal_bag(5), light_tan_bag(3), dull_gold_bag(1)
plaid_olive_bag CONTAIN dim_chartreuse_bag(2)
shiny_orange_bag CONTAIN pale_brown_bag(4), dim_salmon_bag(3)
clear_gray_bag CONTAIN bright_salmon_bag(4), vibrant_crimson_bag(5)
shiny_brown_bag CONTAIN bright_gold_bag(1), clear_tomato_bag(3)
muted_aqua_bag CONTAIN mirrored_indigo_bag(2), dim_tan_bag(1)
plaid_red_bag CONTAIN clear_plum_bag(1)
muted_bronze_bag CONTAIN clear_white_bag(4), dotted_plum_bag(3)
plaid_blue_bag CONTAIN dull_lavender_bag(2), wavy_magenta_bag(5), light_indigo_bag(1)
shiny_salmon_bag CONTAIN dotted_black_bag(2), light_magenta_bag(1)
shiny_cyan_bag CONTAIN faded_violet_bag(5), mirrored_bronze_bag(3), dark_maroon_bag(4), wavy_lavender_bag(2)
drab_magenta_bag CONTAIN light_blue_bag(2), wavy_orange_bag(1), posh_chartreuse_bag(5)
dim_violet_bag CONTAIN dark_red_bag(5), light_violet_bag(4), dotted_fuchsia_bag(2), plaid_tomato_bag(2)
faded_crimson_bag CONTAIN clear_silver_bag(3), vibrant_beige_bag(1)
plaid_fuchsia_bag CONTAIN plaid_red_bag(3), drab_purple_bag(4), clear_lime_bag(4), dim_turquoise_bag(3)
dull_green_bag CONTAIN dotted_beige_bag(5), drab_silver_bag(4), posh_magenta_bag(4), muted_orange_bag(1)
wavy_indigo_bag CONTAIN pale_tan_bag(2)
plaid_lavender_bag CONTAIN dark_black_bag(1)
clear_bronze_bag CONTAIN pale_teal_bag(3)
clear_blue_bag CONTAIN light_teal_bag(2), dotted_olive_bag(5), bright_indigo_bag(3)
posh_aqua_bag CONTAIN light_violet_bag(2), dull_salmon_bag(2), vibrant_violet_bag(1)
dark_gold_bag CONTAIN striped_maroon_bag(2)
vibrant_chartreuse_bag CONTAIN wavy_silver_bag(3)
dark_magenta_bag CONTAIN clear_silver_bag(1)
dim_red_bag CONTAIN wavy_indigo_bag(3), muted_teal_bag(2)
muted_silver_bag CONTAIN pale_crimson_bag(5), dotted_tomato_bag(2)
mirrored_tan_bag CONTAIN pale_salmon_bag(1)
dull_violet_bag CONTAIN dull_black_bag(2)
striped_beige_bag CONTAIN dark_maroon_bag(4), wavy_orange_bag(2)
striped_turquoise_bag CONTAIN light_indigo_bag(3), bright_maroon_bag(5), light_teal_bag(1)
pale_gold_bag CONTAIN dotted_teal_bag(5)
wavy_olive_bag CONTAIN dotted_fuchsia_bag(3)
clear_violet_bag CONTAIN dotted_lavender_bag(1), bright_tan_bag(5), dim_violet_bag(5), drab_salmon_bag(5)
pale_maroon_bag CONTAIN drab_red_bag(4), wavy_yellow_bag(1), muted_green_bag(1), striped_fuchsia_bag(1)
drab_bronze_bag CONTAIN light_gray_bag(4), posh_magenta_bag(3), dull_yellow_bag(1)
vibrant_gold_bag CONTAIN dull_violet_bag(4), clear_white_bag(3), wavy_chartreuse_bag(5), pale_turquoise_bag(4)
clear_beige_bag CONTAIN plaid_blue_bag(4), shiny_plum_bag(3), light_silver_bag(1)
faded_silver_bag CONTAIN drab_turquoise_bag(5), plaid_green_bag(4), posh_yellow_bag(4), plaid_blue_bag(1)
light_brown_bag CONTAIN dark_red_bag(1), dotted_gray_bag(1)
shiny_violet_bag CONTAIN posh_cyan_bag(5), vibrant_plum_bag(5), mirrored_chartreuse_bag(5), plaid_green_bag(4)
dark_bronze_bag CONTAIN bright_gold_bag(4), striped_maroon_bag(2), dark_aqua_bag(4), pale_chartreuse_bag(5)
dull_black_bag CONTAIN vibrant_tomato_bag(2), vibrant_blue_bag(1), pale_yellow_bag(3)
dotted_beige_bag CONTAIN dotted_tomato_bag(5), striped_indigo_bag(1)
clear_indigo_bag CONTAIN dark_violet_bag(3)
bright_coral_bag CONTAIN dark_indigo_bag(1)
drab_turquoise_bag CONTAIN drab_plum_bag(5), pale_magenta_bag(3), drab_red_bag(5), dull_olive_bag(4)
shiny_fuchsia_bag CONTAIN dull_lavender_bag(2), striped_tomato_bag(5)
dull_indigo_bag CONTAIN pale_turquoise_bag(3), faded_tomato_bag(3), dim_magenta_bag(5), drab_indigo_bag(3)
dim_aqua_bag CONTAIN faded_brown_bag(4), mirrored_lime_bag(1)
muted_purple_bag CONTAIN dim_salmon_bag(3), light_violet_bag(4), striped_turquoise_bag(2), shiny_teal_bag(2)
dotted_black_bag CONTAIN dotted_cyan_bag(3), wavy_magenta_bag(4), posh_chartreuse_bag(4)
drab_violet_bag CONTAIN dark_gray_bag(4), dull_chartreuse_bag(5), plaid_gray_bag(4)
plaid_green_bag CONTAIN dark_red_bag(3), wavy_crimson_bag(1), light_coral_bag(4), striped_indigo_bag(4)
faded_brown_bag CONTAIN dark_orange_bag(3)
light_teal_bag CONTAIN striped_indigo_bag(3), dim_bronze_bag(4)
plaid_black_bag CONTAIN mirrored_crimson_bag(2), dim_silver_bag(5), posh_purple_bag(4)
shiny_blue_bag CONTAIN plaid_green_bag(2), plaid_crimson_bag(4), faded_plum_bag(2)
plaid_lime_bag CONTAIN striped_maroon_bag(2)
pale_lavender_bag CONTAIN mirrored_indigo_bag(2), pale_green_bag(1), dim_chartreuse_bag(5), pale_white_bag(3)
drab_chartreuse_bag CONTAIN bright_salmon_bag(1), vibrant_brown_bag(4), muted_violet_bag(1)
light_indigo_bag CONTAIN no_other_bag
plaid_violet_bag CONTAIN dim_white_bag(2), faded_lavender_bag(4)
drab_gold_bag CONTAIN dotted_aqua_bag(5), muted_beige_bag(3), faded_black_bag(4), dark_red_bag(5)
mirrored_bronze_bag CONTAIN plaid_blue_bag(2), light_orange_bag(1)
dim_olive_bag CONTAIN striped_silver_bag(1)
plaid_white_bag CONTAIN pale_turquoise_bag(5), mirrored_orange_bag(4), vibrant_aqua_bag(2)
wavy_purple_bag CONTAIN dark_silver_bag(3), dull_white_bag(1), dotted_magenta_bag(3), dim_salmon_bag(2)
clear_orange_bag CONTAIN striped_indigo_bag(5), wavy_bronze_bag(1), vibrant_blue_bag(4)
plaid_gray_bag CONTAIN dull_aqua_bag(1), dull_olive_bag(3), posh_black_bag(3)
vibrant_violet_bag CONTAIN vibrant_maroon_bag(2)
pale_olive_bag CONTAIN vibrant_fuchsia_bag(2)
muted_brown_bag CONTAIN pale_teal_bag(5), light_brown_bag(2), light_tomato_bag(4)
posh_lavender_bag CONTAIN bright_indigo_bag(4), striped_indigo_bag(1), dark_purple_bag(5)
dotted_blue_bag CONTAIN muted_salmon_bag(4), mirrored_red_bag(3), pale_white_bag(5), clear_red_bag(3)
dim_purple_bag CONTAIN muted_cyan_bag(4)
bright_fuchsia_bag CONTAIN muted_black_bag(5)
vibrant_lime_bag CONTAIN posh_purple_bag(3), drab_aqua_bag(1)
wavy_green_bag CONTAIN drab_red_bag(3), faded_brown_bag(2), wavy_cyan_bag(2)
dull_lime_bag CONTAIN bright_salmon_bag(3), posh_crimson_bag(4), drab_salmon_bag(1), pale_yellow_bag(4)
mirrored_aqua_bag CONTAIN striped_violet_bag(4), striped_indigo_bag(1), striped_tomato_bag(2)
striped_tan_bag CONTAIN light_blue_bag(4), dull_beige_bag(4)
drab_green_bag CONTAIN muted_silver_bag(5), vibrant_orange_bag(1), striped_indigo_bag(2), striped_tomato_bag(4)
dotted_orange_bag CONTAIN mirrored_white_bag(5), muted_orange_bag(5), drab_tomato_bag(2), dull_white_bag(2)
dim_tomato_bag CONTAIN dull_lavender_bag(2)
dull_magenta_bag CONTAIN faded_brown_bag(3), faded_teal_bag(5)
faded_maroon_bag CONTAIN posh_brown_bag(4), dotted_aqua_bag(2)
plaid_cyan_bag CONTAIN faded_crimson_bag(4), light_chartreuse_bag(4), light_crimson_bag(1), posh_fuchsia_bag(1)
dim_salmon_bag CONTAIN dotted_olive_bag(1), light_indigo_bag(4)
faded_chartreuse_bag CONTAIN bright_gold_bag(4), clear_silver_bag(4)
light_plum_bag CONTAIN dotted_chartreuse_bag(2), drab_white_bag(1)
posh_silver_bag CONTAIN mirrored_black_bag(3), dull_blue_bag(4)
dull_salmon_bag CONTAIN dim_white_bag(4), clear_tomato_bag(5), mirrored_maroon_bag(2)
light_green_bag CONTAIN plaid_chartreuse_bag(4), vibrant_aqua_bag(5)
posh_indigo_bag CONTAIN dull_olive_bag(2), dotted_lime_bag(2), drab_red_bag(1)
dark_blue_bag CONTAIN dotted_green_bag(5), wavy_crimson_bag(3), clear_silver_bag(4)
bright_black_bag CONTAIN posh_bronze_bag(5), bright_cyan_bag(3), muted_black_bag(5)
bright_lavender_bag CONTAIN shiny_indigo_bag(1), dim_yellow_bag(1), wavy_yellow_bag(1)
faded_white_bag CONTAIN dotted_black_bag(1), wavy_red_bag(5)
muted_black_bag CONTAIN mirrored_aqua_bag(1), dark_red_bag(4), dull_yellow_bag(5)
light_turquoise_bag CONTAIN shiny_plum_bag(3)
vibrant_coral_bag CONTAIN shiny_orange_bag(2), bright_olive_bag(4)
vibrant_aqua_bag CONTAIN wavy_crimson_bag(2), muted_orange_bag(2)
dotted_tan_bag CONTAIN light_indigo_bag(1), dim_magenta_bag(2)
posh_yellow_bag CONTAIN faded_lavender_bag(4)
pale_lime_bag CONTAIN mirrored_orange_bag(4), dull_gray_bag(3), muted_magenta_bag(1)
drab_white_bag CONTAIN faded_tan_bag(2), wavy_aqua_bag(3)
shiny_tomato_bag CONTAIN dim_coral_bag(4), dotted_lime_bag(3)
wavy_plum_bag CONTAIN bright_orange_bag(1)
dull_crimson_bag CONTAIN pale_silver_bag(2), light_beige_bag(1), wavy_violet_bag(4)
dotted_violet_bag CONTAIN light_indigo_bag(4), dark_black_bag(1), pale_green_bag(3)
dark_salmon_bag CONTAIN light_tan_bag(5), dim_chartreuse_bag(4), faded_green_bag(5), light_brown_bag(3)
dull_brown_bag CONTAIN mirrored_aqua_bag(5), dim_magenta_bag(5), light_brown_bag(4), plaid_black_bag(5)
shiny_chartreuse_bag CONTAIN wavy_yellow_bag(5), faded_aqua_bag(3), bright_fuchsia_bag(1), drab_plum_bag(5)
muted_red_bag CONTAIN drab_white_bag(3), dim_beige_bag(5), bright_olive_bag(4)
posh_blue_bag CONTAIN dotted_beige_bag(1), vibrant_cyan_bag(1), vibrant_brown_bag(4), clear_turquoise_bag(2)
wavy_bronze_bag CONTAIN wavy_turquoise_bag(4), dim_bronze_bag(4), shiny_beige_bag(3), dull_lavender_bag(2)
posh_beige_bag CONTAIN muted_gray_bag(3), light_salmon_bag(4), striped_turquoise_bag(5)
vibrant_red_bag CONTAIN muted_blue_bag(5)
dark_olive_bag CONTAIN dark_maroon_bag(5)
dotted_gray_bag CONTAIN wavy_magenta_bag(3)
vibrant_cyan_bag CONTAIN dotted_lavender_bag(5), vibrant_orange_bag(3)
dark_chartreuse_bag CONTAIN pale_white_bag(3), dull_lavender_bag(1)
faded_lime_bag CONTAIN clear_green_bag(4), shiny_plum_bag(3), light_green_bag(2)
vibrant_blue_bag CONTAIN wavy_turquoise_bag(1), dim_salmon_bag(4)
dull_tan_bag CONTAIN dim_chartreuse_bag(3), plaid_tomato_bag(1), dark_brown_bag(4)
muted_gray_bag CONTAIN clear_tan_bag(4), wavy_aqua_bag(3), dim_white_bag(5)
clear_yellow_bag CONTAIN drab_white_bag(1), dark_salmon_bag(5), dull_yellow_bag(2)
clear_tomato_bag CONTAIN dotted_gray_bag(2), vibrant_beige_bag(5), bright_maroon_bag(1), drab_green_bag(2)
shiny_tan_bag CONTAIN posh_lavender_bag(5), pale_yellow_bag(5)
dark_black_bag CONTAIN muted_purple_bag(4), light_gray_bag(5), drab_red_bag(5)
striped_plum_bag CONTAIN dull_red_bag(3), dark_tomato_bag(1), dark_yellow_bag(4), plaid_cyan_bag(5)
light_gray_bag CONTAIN plaid_chartreuse_bag(3)
light_aqua_bag CONTAIN wavy_magenta_bag(4), light_black_bag(3)
vibrant_brown_bag CONTAIN bright_blue_bag(1), posh_black_bag(1)
posh_tomato_bag CONTAIN wavy_magenta_bag(5)
dotted_bronze_bag CONTAIN mirrored_chartreuse_bag(4)
mirrored_violet_bag CONTAIN clear_maroon_bag(2), light_red_bag(1), mirrored_gray_bag(4)
dark_purple_bag CONTAIN bright_blue_bag(5), plaid_blue_bag(3)
faded_beige_bag CONTAIN plaid_bronze_bag(4), vibrant_turquoise_bag(5), pale_orange_bag(3), mirrored_aqua_bag(5)
mirrored_green_bag CONTAIN dotted_fuchsia_bag(1), light_indigo_bag(5), shiny_beige_bag(3)
striped_violet_bag CONTAIN drab_silver_bag(5), dim_crimson_bag(2), plaid_blue_bag(3)
mirrored_tomato_bag CONTAIN light_lavender_bag(5)
posh_purple_bag CONTAIN pale_orange_bag(3)
dim_blue_bag CONTAIN dotted_plum_bag(5), light_orange_bag(1), dim_maroon_bag(4)
dark_cyan_bag CONTAIN vibrant_white_bag(4), dull_white_bag(4), posh_purple_bag(1)
drab_beige_bag CONTAIN dull_purple_bag(5)
vibrant_olive_bag CONTAIN light_silver_bag(5)
plaid_beige_bag CONTAIN muted_silver_bag(3), vibrant_orange_bag(4)
wavy_silver_bag CONTAIN dim_crimson_bag(2), shiny_maroon_bag(4), pale_indigo_bag(4)
posh_crimson_bag CONTAIN light_violet_bag(2), pale_coral_bag(4), plaid_bronze_bag(3)
vibrant_crimson_bag CONTAIN dull_red_bag(3)
dotted_olive_bag CONTAIN no_other_bag
mirrored_beige_bag CONTAIN plaid_gray_bag(2), mirrored_yellow_bag(5)
bright_brown_bag CONTAIN faded_aqua_bag(2), dim_tomato_bag(1), posh_magenta_bag(5)
bright_magenta_bag CONTAIN posh_gray_bag(2), dim_salmon_bag(3)
clear_magenta_bag CONTAIN dim_cyan_bag(2), clear_red_bag(3), dull_fuchsia_bag(1), wavy_coral_bag(4)
clear_lime_bag CONTAIN dull_green_bag(5), shiny_bronze_bag(2), faded_orange_bag(2), bright_beige_bag(1)
muted_tan_bag CONTAIN vibrant_maroon_bag(4), vibrant_black_bag(3), shiny_maroon_bag(5), vibrant_turquoise_bag(5)
pale_beige_bag CONTAIN light_tomato_bag(3)
dark_fuchsia_bag CONTAIN faded_brown_bag(2), dotted_lavender_bag(3), shiny_teal_bag(4), bright_blue_bag(2)
dim_magenta_bag CONTAIN posh_chartreuse_bag(4)
bright_aqua_bag CONTAIN drab_violet_bag(5)
striped_crimson_bag CONTAIN bright_green_bag(2)
dull_chartreuse_bag CONTAIN plaid_bronze_bag(4), shiny_gray_bag(2), dull_lavender_bag(4)
wavy_chartreuse_bag CONTAIN vibrant_tomato_bag(1), dim_tomato_bag(1), pale_green_bag(3), posh_plum_bag(1)
dotted_white_bag CONTAIN dark_teal_bag(1), dotted_violet_bag(4), bright_beige_bag(5), dim_silver_bag(3)
mirrored_purple_bag CONTAIN posh_green_bag(1)
faded_bronze_bag CONTAIN dotted_indigo_bag(4)
faded_lavender_bag CONTAIN muted_purple_bag(3)
clear_turquoise_bag CONTAIN muted_orange_bag(4), striped_violet_bag(1), clear_tan_bag(5), dim_white_bag(5)
shiny_plum_bag CONTAIN dim_crimson_bag(4)
wavy_fuchsia_bag CONTAIN dotted_brown_bag(3), dark_magenta_bag(5), dark_bronze_bag(2)
faded_olive_bag CONTAIN plaid_indigo_bag(5)
mirrored_orange_bag CONTAIN striped_violet_bag(4), light_violet_bag(2), shiny_orange_bag(4)
pale_indigo_bag CONTAIN shiny_indigo_bag(3)
faded_tan_bag CONTAIN shiny_maroon_bag(3), posh_aqua_bag(5), striped_violet_bag(1), dim_white_bag(2)
bright_chartreuse_bag CONTAIN posh_black_bag(1), bright_gray_bag(5), plaid_chartreuse_bag(3)
drab_blue_bag CONTAIN pale_violet_bag(1), vibrant_green_bag(4)
posh_tan_bag CONTAIN shiny_lime_bag(4)
plaid_maroon_bag CONTAIN dotted_black_bag(2)
dull_coral_bag CONTAIN posh_coral_bag(4), dotted_silver_bag(1), drab_beige_bag(5), plaid_red_bag(1)
striped_yellow_bag CONTAIN plaid_tomato_bag(1), dotted_lavender_bag(1)
muted_magenta_bag CONTAIN muted_black_bag(4)
dotted_cyan_bag CONTAIN vibrant_tomato_bag(1), light_indigo_bag(3), wavy_turquoise_bag(1)
dim_lavender_bag CONTAIN muted_black_bag(1), pale_white_bag(4), mirrored_coral_bag(2), pale_brown_bag(5)
bright_gold_bag CONTAIN vibrant_green_bag(5)
light_white_bag CONTAIN striped_lime_bag(2), muted_lime_bag(2), muted_brown_bag(5), bright_green_bag(4)
wavy_lavender_bag CONTAIN vibrant_purple_bag(2), posh_white_bag(5)
clear_black_bag CONTAIN posh_turquoise_bag(2), dotted_orange_bag(3), faded_teal_bag(3)
muted_crimson_bag CONTAIN pale_violet_bag(1), drab_lavender_bag(5)
posh_green_bag CONTAIN vibrant_beige_bag(4), dark_purple_bag(5), dim_salmon_bag(3), light_black_bag(3)
vibrant_silver_bag CONTAIN posh_coral_bag(3), posh_white_bag(4)
dim_coral_bag CONTAIN posh_violet_bag(2), dark_cyan_bag(1), shiny_green_bag(3), vibrant_cyan_bag(3)
striped_red_bag CONTAIN muted_olive_bag(5), wavy_teal_bag(4), shiny_gray_bag(3), mirrored_coral_bag(1)
bright_violet_bag CONTAIN shiny_beige_bag(3), wavy_magenta_bag(1), light_indigo_bag(5)
vibrant_magenta_bag CONTAIN striped_salmon_bag(4), light_tan_bag(1)
faded_gold_bag CONTAIN light_tomato_bag(5), wavy_black_bag(1), faded_maroon_bag(4)
muted_plum_bag CONTAIN vibrant_brown_bag(1), muted_cyan_bag(2), muted_salmon_bag(4)
plaid_gold_bag CONTAIN shiny_beige_bag(5), faded_fuchsia_bag(3), vibrant_cyan_bag(5), shiny_gold_bag(5)
striped_indigo_bag CONTAIN no_other_bag
wavy_gray_bag CONTAIN plaid_indigo_bag(2), clear_tomato_bag(3), dull_blue_bag(4)
plaid_silver_bag CONTAIN clear_salmon_bag(5), faded_lime_bag(5), shiny_tan_bag(4), mirrored_chartreuse_bag(5)
plaid_yellow_bag CONTAIN shiny_chartreuse_bag(4), light_lime_bag(1), dull_green_bag(2)
plaid_turquoise_bag CONTAIN dotted_aqua_bag(3), posh_magenta_bag(3)
striped_olive_bag CONTAIN faded_aqua_bag(2), dotted_orange_bag(5), dull_turquoise_bag(5), pale_violet_bag(1)
faded_teal_bag CONTAIN striped_indigo_bag(3)
dull_red_bag CONTAIN mirrored_gray_bag(1), drab_coral_bag(4), bright_plum_bag(2), dull_green_bag(1)
dull_gold_bag CONTAIN bright_blue_bag(5)
shiny_magenta_bag CONTAIN light_white_bag(1)
striped_green_bag CONTAIN clear_blue_bag(1)
dull_teal_bag CONTAIN dark_purple_bag(3), dim_lime_bag(4), clear_chartreuse_bag(5)
faded_magenta_bag CONTAIN shiny_gray_bag(4), pale_crimson_bag(5), light_coral_bag(5), pale_white_bag(2)
pale_tomato_bag CONTAIN dull_black_bag(4), posh_chartreuse_bag(1), faded_cyan_bag(1)
muted_blue_bag CONTAIN striped_white_bag(5), faded_orange_bag(1)
light_blue_bag CONTAIN posh_white_bag(4)
plaid_chartreuse_bag CONTAIN bright_gray_bag(2)
dull_aqua_bag CONTAIN clear_tan_bag(5), dotted_red_bag(5), vibrant_tomato_bag(5)
light_lavender_bag CONTAIN clear_fuchsia_bag(5), striped_olive_bag(1)
bright_green_bag CONTAIN vibrant_violet_bag(4), vibrant_maroon_bag(2)
light_beige_bag CONTAIN striped_maroon_bag(1)
drab_indigo_bag CONTAIN posh_tomato_bag(4), faded_brown_bag(5)
dotted_yellow_bag CONTAIN wavy_violet_bag(3), bright_violet_bag(4), vibrant_lime_bag(4), pale_beige_bag(1)
striped_gold_bag CONTAIN light_indigo_bag(2), dull_red_bag(3), vibrant_beige_bag(5)
muted_indigo_bag CONTAIN bright_purple_bag(5), pale_plum_bag(1), wavy_black_bag(5)
dark_lime_bag CONTAIN faded_blue_bag(2)
shiny_white_bag CONTAIN clear_tan_bag(4), pale_yellow_bag(3), plaid_tomato_bag(5), wavy_turquoise_bag(4)
vibrant_maroon_bag CONTAIN dark_red_bag(4), dull_aqua_bag(2), wavy_aqua_bag(5)
drab_teal_bag CONTAIN shiny_indigo_bag(3)
bright_plum_bag CONTAIN plaid_chartreuse_bag(2)
vibrant_yellow_bag CONTAIN posh_purple_bag(3)
posh_salmon_bag CONTAIN dim_plum_bag(4), pale_yellow_bag(1), shiny_gold_bag(2)
shiny_black_bag CONTAIN dim_magenta_bag(3)
bright_gray_bag CONTAIN no_other_bag
dull_orange_bag CONTAIN dotted_purple_bag(3)
pale_purple_bag CONTAIN bright_cyan_bag(2), drab_teal_bag(2), dotted_gold_bag(2), mirrored_fuchsia_bag(4)
dull_yellow_bag CONTAIN posh_gray_bag(3)
muted_tomato_bag CONTAIN faded_orange_bag(3)
drab_olive_bag CONTAIN dim_maroon_bag(4), bright_turquoise_bag(1), shiny_indigo_bag(3), vibrant_lavender_bag(5)
clear_salmon_bag CONTAIN dim_chartreuse_bag(2), shiny_black_bag(2), dotted_indigo_bag(5), dotted_aqua_bag(3)
posh_black_bag CONTAIN wavy_turquoise_bag(2), shiny_plum_bag(2), mirrored_gold_bag(2)
light_gold_bag CONTAIN shiny_tomato_bag(5), light_cyan_bag(4)
shiny_coral_bag CONTAIN faded_silver_bag(3)
plaid_magenta_bag CONTAIN vibrant_black_bag(1), bright_blue_bag(2)
dotted_teal_bag CONTAIN faded_olive_bag(4), vibrant_brown_bag(5), clear_salmon_bag(3)
striped_purple_bag CONTAIN shiny_bronze_bag(5)
dim_tan_bag CONTAIN light_tan_bag(2), dotted_gold_bag(1), shiny_white_bag(3)
light_silver_bag CONTAIN dotted_cyan_bag(5), dotted_aqua_bag(4)
dull_white_bag CONTAIN striped_turquoise_bag(5)
plaid_aqua_bag CONTAIN dim_bronze_bag(3), dull_brown_bag(5), faded_plum_bag(3), mirrored_crimson_bag(2)
dotted_silver_bag CONTAIN faded_teal_bag(1)
dull_olive_bag CONTAIN dark_turquoise_bag(1), muted_orange_bag(3)
clear_purple_bag CONTAIN drab_salmon_bag(3)
mirrored_plum_bag CONTAIN vibrant_lavender_bag(1)
bright_beige_bag CONTAIN plaid_magenta_bag(4), dull_turquoise_bag(1), dim_white_bag(4), light_aqua_bag(1)
pale_red_bag CONTAIN muted_lavender_bag(1), vibrant_teal_bag(2), plaid_cyan_bag(4), dull_orange_bag(5)
drab_orange_bag CONTAIN bright_plum_bag(3), vibrant_chartreuse_bag(5)
mirrored_gold_bag CONTAIN wavy_magenta_bag(2)
posh_maroon_bag CONTAIN dotted_lime_bag(3), muted_black_bag(2), faded_green_bag(3)
clear_white_bag CONTAIN pale_black_bag(4)
pale_silver_bag CONTAIN dim_coral_bag(2), dull_lavender_bag(2), dark_teal_bag(2), wavy_green_bag(3)
vibrant_tomato_bag CONTAIN dull_lavender_bag(5)
striped_orange_bag CONTAIN shiny_salmon_bag(5), pale_gold_bag(1), mirrored_gray_bag(4), plaid_black_bag(1)
dim_beige_bag CONTAIN dim_salmon_bag(5), striped_yellow_bag(2), shiny_orange_bag(5), light_salmon_bag(5)
clear_gold_bag CONTAIN dim_salmon_bag(2), vibrant_cyan_bag(4)
dim_teal_bag CONTAIN light_indigo_bag(3), pale_green_bag(3), muted_bronze_bag(5)
shiny_silver_bag CONTAIN drab_red_bag(3), pale_magenta_bag(1), plaid_blue_bag(3), pale_white_bag(4)
dark_beige_bag CONTAIN posh_black_bag(4), dark_maroon_bag(1)
bright_bronze_bag CONTAIN mirrored_yellow_bag(4), vibrant_salmon_bag(1), mirrored_teal_bag(2), shiny_beige_bag(1)
dotted_maroon_bag CONTAIN clear_tomato_bag(1)
bright_olive_bag CONTAIN striped_tomato_bag(3), plaid_indigo_bag(3), posh_magenta_bag(3)
faded_tomato_bag CONTAIN bright_violet_bag(5)
mirrored_magenta_bag CONTAIN wavy_coral_bag(3), dull_tan_bag(4), wavy_chartreuse_bag(3)
striped_aqua_bag CONTAIN drab_teal_bag(3), drab_crimson_bag(3), plaid_gold_bag(5), vibrant_aqua_bag(2)
clear_crimson_bag CONTAIN striped_chartreuse_bag(5), vibrant_blue_bag(5)
striped_blue_bag CONTAIN dull_red_bag(4), vibrant_white_bag(3), posh_black_bag(4)
posh_olive_bag CONTAIN muted_cyan_bag(5)
plaid_indigo_bag CONTAIN dotted_fuchsia_bag(5), plaid_chartreuse_bag(2), vibrant_blue_bag(3)
mirrored_lime_bag CONTAIN dotted_lavender_bag(2), wavy_bronze_bag(2)
wavy_blue_bag CONTAIN mirrored_green_bag(5), faded_tomato_bag(5), posh_turquoise_bag(1)
light_fuchsia_bag CONTAIN faded_tomato_bag(3), muted_beige_bag(5), faded_beige_bag(2), wavy_indigo_bag(4)
dull_plum_bag CONTAIN dark_blue_bag(4), shiny_maroon_bag(5), pale_gray_bag(3), drab_lime_bag(5)
drab_fuchsia_bag CONTAIN dark_maroon_bag(3)
pale_teal_bag CONTAIN vibrant_blue_bag(4), bright_green_bag(1), dim_crimson_bag(3), posh_salmon_bag(1)
dull_tomato_bag CONTAIN dim_maroon_bag(3), plaid_gray_bag(4), striped_gold_bag(5), striped_white_bag(5)
pale_orange_bag CONTAIN drab_yellow_bag(4)
wavy_aqua_bag CONTAIN dim_bronze_bag(1)
dim_chartreuse_bag CONTAIN bright_violet_bag(2)
dotted_crimson_bag CONTAIN vibrant_orange_bag(5), wavy_magenta_bag(4)
faded_cyan_bag CONTAIN mirrored_blue_bag(3), shiny_fuchsia_bag(3), bright_indigo_bag(4)
pale_salmon_bag CONTAIN pale_cyan_bag(2), muted_lime_bag(2), vibrant_plum_bag(2)
drab_lime_bag CONTAIN drab_yellow_bag(2), light_magenta_bag(2), dotted_fuchsia_bag(3)
shiny_bronze_bag CONTAIN posh_lavender_bag(1)
dim_fuchsia_bag CONTAIN dotted_gold_bag(5), vibrant_indigo_bag(5), shiny_teal_bag(4), dotted_silver_bag(2)
dark_green_bag CONTAIN shiny_blue_bag(2)
bright_red_bag CONTAIN pale_brown_bag(2), plaid_blue_bag(3), drab_bronze_bag(4), dim_yellow_bag(3)
clear_teal_bag CONTAIN drab_white_bag(2), muted_beige_bag(3)
pale_aqua_bag CONTAIN light_tan_bag(4)
dull_lavender_bag CONTAIN dim_bronze_bag(1), dim_crimson_bag(5), dotted_olive_bag(1)
dotted_plum_bag CONTAIN light_black_bag(1)
shiny_teal_bag CONTAIN light_indigo_bag(3)
dotted_lime_bag CONTAIN shiny_gold_bag(1), plaid_crimson_bag(3)
dark_tan_bag CONTAIN faded_tan_bag(5)
vibrant_indigo_bag CONTAIN shiny_fuchsia_bag(3)
light_tan_bag CONTAIN pale_yellow_bag(4), pale_crimson_bag(1), light_gray_bag(3)
drab_plum_bag CONTAIN shiny_turquoise_bag(2), vibrant_yellow_bag(2), muted_brown_bag(4), drab_lavender_bag(2)
dim_white_bag CONTAIN dark_red_bag(5), dotted_olive_bag(5)
light_red_bag CONTAIN vibrant_indigo_bag(2), wavy_salmon_bag(1), dull_brown_bag(3)
mirrored_fuchsia_bag CONTAIN dotted_tomato_bag(5)
mirrored_indigo_bag CONTAIN pale_lime_bag(5), light_magenta_bag(5), light_gray_bag(4), dull_red_bag(2)
dim_yellow_bag CONTAIN muted_beige_bag(2), plaid_olive_bag(2), faded_aqua_bag(3)
shiny_gray_bag CONTAIN drab_yellow_bag(1), shiny_lavender_bag(3), posh_white_bag(1)
faded_violet_bag CONTAIN bright_olive_bag(2), clear_gray_bag(5), dark_orange_bag(2), pale_magenta_bag(1)
mirrored_black_bag CONTAIN clear_blue_bag(4)
drab_aqua_bag CONTAIN vibrant_crimson_bag(1), clear_fuchsia_bag(4)
pale_black_bag CONTAIN pale_turquoise_bag(5), striped_yellow_bag(4), dotted_beige_bag(4)
wavy_cyan_bag CONTAIN vibrant_brown_bag(1)
dark_silver_bag CONTAIN light_tomato_bag(3), dotted_lavender_bag(5), bright_turquoise_bag(3)
faded_orange_bag CONTAIN clear_turquoise_bag(3), mirrored_gold_bag(3), plaid_bronze_bag(2), dotted_fuchsia_bag(2)
drab_crimson_bag CONTAIN clear_blue_bag(5)
posh_magenta_bag CONTAIN bright_violet_bag(1), dotted_beige_bag(2), bright_gray_bag(2)
posh_brown_bag CONTAIN dim_tomato_bag(3), dim_chartreuse_bag(1), shiny_orange_bag(5)
drab_gray_bag CONTAIN striped_violet_bag(3)
pale_cyan_bag CONTAIN dotted_aqua_bag(5), striped_tomato_bag(3)
wavy_tan_bag CONTAIN pale_indigo_bag(3)
plaid_brown_bag CONTAIN dotted_indigo_bag(2), dull_indigo_bag(1), light_brown_bag(2)
vibrant_beige_bag CONTAIN shiny_teal_bag(1), vibrant_cyan_bag(3), posh_gray_bag(2), striped_tomato_bag(3)
shiny_aqua_bag CONTAIN vibrant_black_bag(2), muted_coral_bag(2), vibrant_coral_bag(4)
mirrored_silver_bag CONTAIN drab_silver_bag(3), clear_turquoise_bag(1)
pale_tan_bag CONTAIN pale_magenta_bag(3)
striped_cyan_bag CONTAIN drab_tomato_bag(5)
mirrored_coral_bag CONTAIN mirrored_crimson_bag(1), bright_maroon_bag(1)
pale_white_bag CONTAIN shiny_beige_bag(4), shiny_maroon_bag(1), dim_bronze_bag(5)
shiny_beige_bag CONTAIN mirrored_gold_bag(3)
mirrored_chartreuse_bag CONTAIN dotted_tomato_bag(1), bright_cyan_bag(2)
wavy_red_bag CONTAIN posh_lavender_bag(1), vibrant_blue_bag(1), muted_brown_bag(3)
muted_chartreuse_bag CONTAIN dim_lavender_bag(3), pale_plum_bag(4), light_magenta_bag(4)
shiny_purple_bag CONTAIN muted_green_bag(4), light_white_bag(5), faded_tan_bag(2), light_beige_bag(5)
clear_tan_bag CONTAIN dotted_red_bag(3), striped_violet_bag(1), plaid_chartreuse_bag(4)
bright_teal_bag CONTAIN faded_black_bag(1), faded_maroon_bag(3)
posh_orange_bag CONTAIN light_gold_bag(5), posh_aqua_bag(3)
striped_gray_bag CONTAIN bright_plum_bag(2), shiny_gray_bag(2)
dim_lime_bag CONTAIN plaid_blue_bag(1)
posh_fuchsia_bag CONTAIN dull_indigo_bag(1), plaid_blue_bag(2)
dotted_tomato_bag CONTAIN no_other_bag
dim_plum_bag CONTAIN dim_chartreuse_bag(1)
dim_orange_bag CONTAIN muted_magenta_bag(2), faded_aqua_bag(5)
posh_gold_bag CONTAIN light_maroon_bag(5), dark_turquoise_bag(4), posh_white_bag(1), wavy_beige_bag(5)
striped_bronze_bag CONTAIN dark_magenta_bag(1)
wavy_lime_bag CONTAIN mirrored_lavender_bag(4), pale_bronze_bag(3), dull_white_bag(1)
pale_magenta_bag CONTAIN dim_crimson_bag(2), plaid_plum_bag(4), muted_silver_bag(5), dim_yellow_bag(2)
striped_chartreuse_bag CONTAIN light_black_bag(5), bright_fuchsia_bag(3), pale_black_bag(4)
vibrant_tan_bag CONTAIN dim_tan_bag(2)
shiny_crimson_bag CONTAIN pale_beige_bag(5), clear_purple_bag(3), pale_violet_bag(2), dotted_chartreuse_bag(4)
vibrant_orange_bag CONTAIN no_other_bag
striped_silver_bag CONTAIN clear_orange_bag(5), dotted_fuchsia_bag(2)
clear_cyan_bag CONTAIN muted_gray_bag(5), wavy_aqua_bag(3)
light_black_bag CONTAIN striped_yellow_bag(1)
muted_white_bag CONTAIN muted_tomato_bag(3), light_black_bag(5), pale_black_bag(4), shiny_gold_bag(5)
TEXT

# INPUT = <<~TEXT.split("\n")
# shiny_gold_bag CONTAIN dark_red_bag(2)
# dark_red_bag CONTAIN dark_orange_bag(2)
# dark_orange_bag CONTAIN dark_yellow_bag(2)
# dark_yellow_bag CONTAIN dark_green_bag(2)
# dark_green_bag CONTAIN dark_blue_bag(2)
# dark_blue_bag CONTAIN dark_violet_bag(2)
# dark_violet_bag CONTAIN no_other_bag
# TEXT

BAGS = INPUT.map do |bag|
  container, *contents = bag.sub('CONTAIN', '').delete(',').split

  contents_counts = contents.map do |content|
    if content == 'no_other_bag'
      ['no_other_bag', 0]
    else
      bag_name, bag_count = content.delete(')').split('(')
      [bag_name, bag_count.to_i]
    end
  end.to_h

  [container, contents_counts]
end.to_h

def sum(container)
  return 0 if container == 'no_other_bag'

  BAGS[container].map { |content, count| count * sum(content) + count }.reduce(:+)
end

puts sum('shiny_gold_bag')
